# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "The Wordsmiths"
description: > # this means to ignore newlines until "email:"
   Blog and Content Production Company

email: thewordsmithstws@gmail.com
#blog logo
logo: "/assets/images/tws_logo.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

authors:
  rohan:
    name: "Rohan Mishra"
    author_image: "/assets/images/rohan.jpg"
  aarman:
    name: "Aarman Roy"
    author_image: "/assets/images/aarman.jpg"
  anvi:
    name: "Anvi Gupta"
    author_image: "/assets/images/anvi.jpg"
  arushi:
    name: "Arushi Chopra"
    author_image: "/assets/images/arushi.jpg"
  ashima:
    name: "Ashima Suvarna"
    author_image: "/assets/images/ashima.jpg"
  chavvi:
    name: "Chavvi Gupta"
    author_image: "/assets/images/chavvi.jpg"
  dakshita:
    name: "Dakshita Joshi"
    author_image: "/assets/images/dakshita.jpg"
  gitanjali:
    name: "Gitanjali Jaggi"
    author_image: "/assets/images/gitanjali.jpg"
  gursifath:
    name: "Gursifath Bhasin"
    author_image: "/assets/images/gursifath.jpg"
  harsh:
    name: "Harsh Pandey"
    author_image: "/assets/images/harsh.jpg"
  raghav:
    name: "Raghav Aggarwal"
    author_image: "/assets/images/raghav.jpg"
  santrupta:
    name: "Santrupta Mishra"
    author_image: "/assets/images/santrupta.jpg"
  shashank:
    name: "Shashank Shekhar Jha"
    author_image: "/assets/images/shashank.jpg"
  shaurya:
    name: "Shaurya Verma"
    author_image: "/assets/images/shaurya.jpg"
  shreyab:
    name: "Shreya Barua"
    author_image: "assets/images/shreyab.jpg"
  shreyag:
    name: "Shreya Garg"
    author_image: "assets/images/shreyag.jpg"
  tanmay:
    name: "Tanmay Garg"
    author_image: "/assets/images/tanmay.jpg"
  shreyasee:
    name: "Shreyasee Bathsyo"
    author_image: "/assets/images/shreyasee.jpg"
  shubhi:
    name: "Shubhi Srivastava"
    author_image: "/assets/images/shubhi.jpg"
  guest:
    name: "Guest Post"
    author_image: "/assets/images/guest.jpg"

# paginate:	5

url: "http://thewordsmiths.xyz" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
#twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
 # - icon:	twitter
  #  url:	https://twitter.com/dirkfabisch
  #  desc: Follow me on twitter
  #  share_url: http://twitter.com/share
  #  share_title: ?text=
  #  share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/wordsmithstws
    desc: Connect with us on Facebook!
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

#  - icon:	github
#    url:	https://github.com/dirkfabisch
#    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

 # - icon: medium
 #   url: https://medium.com/the-wordsmiths
  #  desc: We love Medium.
   # share_url:
   # share_title:
   # share_link:

  - icon: tumblr
    url: "https://www.tumblr.com/blog/wordsmithstws"
    desc: Tumblr is Love.
    share_url: 
    share_title:
    share_link:

  - icon: instagram
    url: https://www.instagram.com/wordsmithstws/
    desc: Instantly Follow us!
    share_url:
    share_title:
    share_link:

  - icon: pinterest
    url:
    desc: I don't know what it is.
    share_url:
    share_title:
    share_link:
